var hierarchy =
[
    [ "CEP", "class_c_e_p.html", null ],
    [ "Classe", "class_classe.html", null ],
    [ "CodigoDeAgencia", "class_codigo_de_agencia.html", null ],
    [ "CodigoDeAplicacao", "class_codigo_de_aplicacao.html", null ],
    [ "CodigoDeBanco", "class_codigo_de_banco.html", null ],
    [ "CodigoDeProduto", "class_codigo_de_produto.html", null ],
    [ "CPF", "class_c_p_f.html", null ],
    [ "Data", "class_data.html", null ],
    [ "Emissor", "class_emissor.html", null ],
    [ "Endereco", "class_endereco.html", null ],
    [ "Horario", "class_horario.html", null ],
    [ "Nome", "class_nome.html", null ],
    [ "Numero", "class_numero.html", null ],
    [ "Prazo", "class_prazo.html", null ],
    [ "ResultadoTU", "class_resultado_t_u.html", null ],
    [ "Senha", "class_senha.html", null ],
    [ "Taxa", "class_taxa.html", null ],
    [ "TU", null, [
      [ "TUCEP", "class_t_u_c_e_p.html", null ],
      [ "TUClasse", "class_t_u_classe.html", null ],
      [ "TUCodigoDeAgencia", "class_t_u_codigo_de_agencia.html", null ],
      [ "TUCodigoDeAplicacao", "class_t_u_codigo_de_aplicacao.html", null ],
      [ "TUCodigoDeBanco", "class_t_u_codigo_de_banco.html", null ],
      [ "TUCodigoDeProduto", "class_t_u_codigo_de_produto.html", null ],
      [ "TUCPF", "class_t_u_c_p_f.html", null ],
      [ "TUData", "class_t_u_data.html", null ],
      [ "TUEmissor", "class_t_u_emissor.html", null ],
      [ "TUEndereco", "class_t_u_endereco.html", null ],
      [ "TUHorario", "class_t_u_horario.html", null ],
      [ "TUNome", "class_t_u_nome.html", null ],
      [ "TUNumero", "class_t_u_numero.html", null ],
      [ "TUPrazo", "class_t_u_prazo.html", null ],
      [ "TUSenha", "class_t_u_senha.html", null ],
      [ "TUTaxa", "class_t_u_taxa.html", null ],
      [ "TUValorDeAplicacao", "class_t_u_valor_de_aplicacao.html", null ],
      [ "TUValorMinimo", "class_t_u_valor_minimo.html", null ]
    ] ],
    [ "ValorDeAplicacao", "class_valor_de_aplicacao.html", null ],
    [ "ValorMinimo", "class_valor_minimo.html", null ]
];