CREATE TABLE "PRODUTOS" (
	"CODIGO_DE_PRODUTO"	TEXT,
	"CLASSE"	TEXT,
	"EMISSOR"	TEXT,
	"PRAZO"	INTEGER,
	"DATA"	TEXT,
	"TAXA"	REAL,
	"HORARIO"	TEXT,
	"VALOR_MINIMO"	INTEGER,
	PRIMARY KEY("CODIGO_DE_PRODUTO")
);